apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: amazona
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ivona1111/amazona-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: amazona-secret
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: amazona-secret
                  key: JWT_SECRET
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: amazona-config
                  key: NODE_ENV