apiVersion: v1
kind: Secret
metadata:
  name: amazona-secret
  namespace: amazona
type: Opaque
stringData:
  MONGO_ROOT_PASSWORD: secret
  JWT_SECRET: somesecret
  MONGODB_URI: mongodb://admin:secret@mongodb:27017/amazona?authSource=admin